apiVersion: v1
kind: Service
metadata:
  name: pma-service
  labels:
    app: pma-service
spec:
  ports:
  - port: 80
    name: web
    targetPort: 80
  type: NodePort
  selector:
    app: pma
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  labels:
    app: pma
spec:
  selector:
    matchLabels:
      app: pma # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: pma # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pma
        image: phpmyadmin:latest
        ports:
        - containerPort: 80
          name: web
        envFrom:
        - configMapRef:
            name: configmap-app
        - secretRef:
            name: secret-app
        volumeMounts:
        - name: www2
          mountPath: /etc/phpmyadmin/config.user.inc.php
      volumes:
      - name: www2
        persistentVolumeClaim:
          claimName: www2-pvc


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-storage

