apiVersion: v1
kind: PersistentVolume
metadata:
  name: per-vol-1
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-storage
  hostPath:
    path: /data

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: per-vol-2
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-storage
  hostPath:
    path: /data
