apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  ports:
  - port: 3306
    name: web
  selector:
    app: mysql-elastio
---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-elastio
spec:
  selector:
    matchLabels:
      app: mysql-elastio # has to match .spec.template.metadata.labels
  serviceName: "mysql-service"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mysql-elastio # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: elestio/mysql
        ports:
        - containerPort: 3306
          name: web
        envFrom:
        - secretRef:
            name: secret-app      
        volumeMounts:
        - name: www
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "sc-storage"
      resources:
        requests:
          storage: 1Gi
